[package]
authors = [
    "Damien Martin-Guillerez <dmarting@google.com>",
    "Facebook",
]
categories = ["parser-implementations", "development-tools"]
description = "LSP bindings for starlark"
documentation = "https://docs.rs/starlark"
edition = "2024"
keywords = ["starlark", "skylark", "language", "interpreter"]
license = "Apache-2.0"
name = "starlark_lsp"
repository = "https://github.com/facebook/starlark-rust"
version = "0.13.0"

[dependencies]
anyhow = "1.0.65"
derivative = "2.2"
derive_more.workspace = true
dupe = { workspace = true }
itertools = "0.14.0"
lsp-server = "0.7.2"
lsp-types = "0.94.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.18"

starlark = { version = "0.13.0", path = "../starlark" }
starlark_syntax = { version = "0.13.0", path = "../starlark_syntax" }

[dev-dependencies]
maplit = "1.0.2"
regex = "1.5.4"
textwrap = "0.11"
