[package]
description = "A Rust-centric companion tool to Buck for usage in IDEs."
edition = "2024"
license = { workspace = true }
name = "rust-project"
readme = "README.md"
repository = { workspace = true }
version = "0.0.0"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
dunce = { workspace = true }
elf = "0.8.0"
lsp-server = { workspace = true }
lsp-types = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = { workspace = true }
tracing = { workspace = true }
tracing-core = "0.1.32"
tracing-subscriber = { workspace = true }
whoami = "1.4.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fbcode_build)"] }
