[package]
authors = ["Facebook"]
categories = ["rust-patterns"]
description = "Comparison for &dyn types"
documentation = "https://docs.rs/cmp_any"
edition = "2021"
license = { workspace = true }
name = "cmp_any"
repository = "https://github.com/facebookincubator/gazebo"
version = "0.8.1"
