[package]
name = "buck2_bxl"
version = "0.1.0"
edition = "2021"
description = "Buck V2 extension language"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
ctor = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
structopt = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

fbinit = { workspace = true }

allocative = { workspace = true }
gazebo = { workspace = true }
display_container = { workspace = true }
dupe = { workspace = true }
dice = { workspace = true }
buck2_events = { workspace = true }
starlark = { workspace = true }
starlark_map = { workspace = true }
more_futures = { workspace = true }

buck2_build_api = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_execute = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
buck2_node = { workspace = true }
buck2_profile = { workspace = true }
buck2_query = { workspace = true }
buck2_query_parser = { workspace = true }
buck2_server_ctx = { workspace = true }
buck2_cli_proto = { workspace = true }

[dev-dependencies]
maplit = { workspace = true }
