[package]
description = "Buck V2 extension language"
edition = "2021"
name = "buck2_bxl"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-recursion = { workspace = true }
async-scoped = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
higher-order-closure = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
num-bigint = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
structopt = { workspace = true }
tokio = { workspace = true }

fbinit = { workspace = true }

allocative = { workspace = true }
buck2_events = { workspace = true }
cmp_any = { workspace = true }
dice = { workspace = true }
display_container = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
more_futures = { workspace = true }
starlark = { workspace = true }
starlark_map = { workspace = true }

buck2_analysis = { workspace = true }
buck2_artifact = { workspace = true }
buck2_build_api = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_configured = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_execute = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_node = { workspace = true }
buck2_profile = { workspace = true }
buck2_query = { workspace = true }
buck2_query_parser = { workspace = true }
buck2_server_ctx = { workspace = true }
buck2_util = { workspace = true }

[dev-dependencies]
provider = { workspace = true }

ctor = { workspace = true }
maplit = { workspace = true }
