[package]
description = "Tests for buck2_interpreter_for_build"
edition = "2021"
license = { workspace = true }
name = "buck2_interpreter_for_build_tests"
repository = { workspace = true }
version = "0.1.0"

[dev-dependencies]
ctor = { workspace = true }
indoc = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

dice = { workspace = true }
dupe = { workspace = true }
futures = { workspace = true }
gazebo = { workspace = true }
starlark = { workspace = true }

buck2_build_api = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
buck2_node = { workspace = true }
buck2_query = { workspace = true }
buck2_transition = { workspace = true }
