[package]
name = "dice_examples"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
async-trait = "0.1.24"
derive_more = "0.99.3"
futures = "0.3"
ref-cast = "1.0.0"
dupe = { workspace = true }
gazebo = { workspace = true }
gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
more_futures = { path = "../../shed/more_futures" }
allocative = { workspace = true }

dice = { path = "../dice" }

[dev-dependencies]
cast = "0.2.3"
futures = "0.3"
anyhow = "1.0.65"
paste = "1.0" # !
tokio = { version = "1.5", features = ["full"]}

[features]
# @oss-disable: default = ["gazebo_lint"]
