[package]
name = "dice_examples"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
async-trait = "0.1.24"
derive_more = "0.99.3"
futures = "0.3"
ref-cast = "1.0.0"

gazebo.version = "0.7.1"
gazebo.features = ["str_pattern_extensions"]
# @oss-disable: gazebo.path = "../../gazebo/gazebo"
gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"

dice = { path = "../dice" }

[dev-dependencies]
# Newer cast pull in semver 1.0, which fails with
# https://github.com/dtolnay/semver/issues/251
criterion = { version = "0.3.4", features = ["async", "async_tokio"] }
cast = "=0.2.6"
futures = "0.3"
anyhow = "1.0.51"
paste = "1.0" # !
tokio = { version = "1.5", features = ["full"]}

[features]
# @oss-disable: default = ["gazebo_lint"]

[[bench]]
name = "math_computation"
harness = false

[[bench]]
name = "supply_chain"
harness = false
