[package]
description = "Tests for buck2_build_api crate"
edition = "2024"
license = { workspace = true }
name = "buck2_build_api_tests"
repository = { workspace = true }
version = "0.1.0"

[dev-dependencies]
assert_matches = { workspace = true }
async-trait = { workspace = true }
ctor = { workspace = true }
derivative = { workspace = true }
fxhash = { workspace = true }
indexmap = { workspace = true }
indoc = { workspace = true }
maplit = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

sorted_vector_map = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
itertools = { workspace = true }
starlark = { workspace = true }
starlark_map = { workspace = true }

buck2_action_impl = { workspace = true }
buck2_analysis = { workspace = true }
buck2_anon_target = { workspace = true }
buck2_artifact = { workspace = true }
buck2_build_api = { workspace = true }
buck2_build_signals = { workspace = true }
buck2_certs = { workspace = true }
buck2_common = { workspace = true }
buck2_configured = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_directory = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_file_watcher = { workspace = true }
buck2_fs = { workspace = true }
buck2_http = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
buck2_node = { workspace = true }
buck2_transition = { workspace = true }
buck2_util = { workspace = true }
