[package]
description = "Code supporting buck2 event log handling"
edition = "2024"
license = { workspace = true }
name = "buck2_event_log"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
async-compression = { workspace = true }
chrono = { workspace = true }
dupe = { workspace = true }
futures = { workspace = true }
gazebo = { workspace = true }
itertools = { workspace = true }
pin-project = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shlex = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_event_observer = { workspace = true }
buck2_events = { workspace = true }
buck2_fs = { workspace = true }
buck2_util = { workspace = true }
buck2_wrapper_common = { workspace = true }

[dev-dependencies]
maplit = { workspace = true }
tempfile = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(tokio_unstable)"] }
