omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]
OUT_DIR = "."

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = '''
Unresolved build script at vendor/unicode-linebreak-0.1.4/build.rs. Dependencies:
    hashbrown-0.12.3
    regex-1.6.0'''

[extra_mapped_srcs]

[platform_fixup]
