[package]
name = "dice"
version = "0.1.0"
edition = "2021"

[dependencies]
anymap = "0.12.1"
async-trait = "0.1.24"
bincode = "1.3.3"
dashmap = "4.0.2"
derive_more = "0.99.3"
futures = "0.3"
indexmap = { version = "1.6", features = ["serde-1"] }
itertools = "0.10.0"
maplit = "1.0.2"
more_futures = { path = "../../shed/more_futures" }
once_cell = "1.3"
tokio = { version = "1.5", features = ["full"]}
gazebo.version = "0.7.0"
gazebo.features = ["str_pattern_extensions"]
# @oss-disable: gazebo.path = "../../gazebo/gazebo"
gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
owning_ref = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.24"
tracing = "0.1.22"
parking_lot = { version = "0.11.2", features = ["send_guard"] }
lock_api = ">=0.4, <0.4.7" # Not using this as an explicit dep, but lock_api 0.4.7 is only compatible with latest nightly
anyhow = "1.0.51"

[features]
# @oss-disable: default = ["gazebo_lint"]

[dev-dependencies]
# Newer cast pull in semver 1.0, which fails with
# https://github.com/dtolnay/semver/issues/251
criterion = { version = "0.3.4", features = ["async", "async_tokio"] }
cast = "=0.2.6"
derivative = "2.1.1"
tempfile = "3.1"
anyhow = "1.0.51"
tokio = { version = "1.5", features = ["full"]}
