[package]
edition = "2024"
license = { workspace = true }
name = "dice"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
anyhow = "1.0.65"
anymap3 = "1.0.1"
async-trait = "0.1.24"
cmp_any = { workspace = true }
dashmap = "5.5.3"
derivative = { workspace = true }
derive_more = { version = "1.0.0", features = ["full"] }
dice_error = { path = "../dice_error" }
dice_futures = { path = "../dice_futures" }
dupe = { workspace = true }
futures = "0.3"
fxhash = "0.2.1"
gazebo = { workspace = true }
indoc = { workspace = true }
itertools = "0.13.0"
lock_free_hashtable = { workspace = true }
lock_free_vec = { workspace = true }
parking_lot = { version = "0.11.2", features = ["send_guard"] }
ref-cast = { workspace = true }
scopeguard = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
slab = "0.4.7"
# @oss-disable: sorted_vector_map.path = "../../../common/rust/shed/sorted_vector_map"
sorted_vector_map.git = "https://github.com/facebookexperimental/rust-shed" # @oss-enable
sorted_vector_map.version = "0.2"
static_assertions = { workspace = true }
take_mut = { workspace = true }
thiserror = "1.0.36"
tokio = { version = "1.5", features = ["full"] }
tracing = "0.1.22"
triomphe = { workspace = true }
typed-arena = { workspace = true }

[dev-dependencies]
anyhow = "1.0.65"
assert_matches = "1.5"
bincode = { workspace = true }
derivative = "2.1.1"
tempfile = "3.1"
tokio = { version = "1.5", features = ["full"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fbcode_build)"] }
