[package]
description = "Lock-free (almost) insertion only hashtable"
edition = "2021"
name = "lock_free_hashtable"
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
atomic = { workspace = true }
parking_lot = "0.12.1"

[dev-dependencies]
num_cpus = { workspace = true }
