[package]
name = "lock_free_hashtable"
version = "0.1.0"
edition = "2021"
description = "Lock-free (almost) insertion only hashtable"

[dependencies]
allocative = { workspace = true }
atomic = { workspace = true }
parking_lot = "0.11.2"

[dev-dependencies]
num_cpus = { workspace = true }
