[package]
name = "starlark_syntax"
edition = "2021"
version = "0.9.0"
license = "Apache-2.0"
description = "Starlark language AST"
documentation = "https://docs.rs/starlark"
repository = "https://github.com/facebookexperimental/starlark-rust"
authors = [
    "Damien Martin-Guillerez <dmarting@google.com>",
    "Facebook",
]
keywords = ["starlark", "skylark", "bazel", "language", "interpreter"]
categories = ["parser-implementations", "development-tools"]

[dependencies]
annotate-snippets = { version = "0.9.0", features = [] }
anyhow = { workspace = true }
derive_more = { workspace = true }
once_cell = "1.8"
lsp-types = "0.94.1"
memchr = { workspace = true }

allocative = { workspace = true }
dupe = { workspace = true }
