[package]
name = "buck2_transition"
version = "0.1.0"
edition = "2021"
description = "Implementation of configuration transition"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
itertools = { workspace = true }
thiserror = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
more_futures = { workspace = true }
starlark = { workspace = true }
starlark_map = { workspace = true }

buck2_build_api = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_events = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_node = { workspace = true }
