[package]
description = "`buck2 completion` command client implementation"
edition = "2024"
license = { workspace = true }
name = "buck2_cmd_completion_client"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }

buck2_cli_proto = { workspace = true }
buck2_client_ctx = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_error = { workspace = true }
buck2_fs = { workspace = true }

[dev-dependencies]
paste = { workspace = true }

[lints]
workspace = true
