cargo-features = ['named-profiles']

[workspace]
resolver = "2"
members = [
    # @oss-disable: "attic/uniplate",
    # @oss-disable: "attic/uniplate_derive",
    "app/buck2_protoc_dev",
    "buck2_audit",
    "buck2_bxl",
    "buck2_core",
    "buck2_data",
    "buck2_events",
    "buck2_query",
    "buck2_query_parser",
    "buck2_query_derive",
    "buck2_test_proto",
    # @oss-disable: "buck2_tpx",
    # @oss-disable: "buck2_tpx_cli",
    "buck2_build_api",
    "buck2_build_api_derive",
    "buck2_client",
    "buck2_common",
    "buck2_grpc",
    "buck2_interpreter",
    "buck2_interpreter_for_build",
    "buck2_forkserver",
    "buck2_forkserver_proto",
    "buck2_node",
    "buck2_execute",
    "buck2_execute_impl",
    "buck2_server",
    "buck2_server_commands",
    "buck2_server_ctx",
    "buck2_test",
    "buck2_test_api",
    "cli",
    "cli_proto",
    "dice/dice",
    "dice/dice_examples",
    # @oss-disable: "dice/fuzzy_dice",
    # @oss-disable: "dice_replay",
    "downward_api",
    "downward_api_proto",
    # @oss-disable: "host_sharing",
    # @oss-disable: "gazebo_lint/gazebo_lint",
    # Uncomment to manually test linter_test
    # "gazebo_lint/linter_test",
    # @oss-disable: "gazebo/gazebo",
    # @oss-disable: "gazebo/gazebo_derive",
    "remote_execution/stub",
    "starlark-rust/starlark",
    "starlark-rust/starlark_derive",
    "starlark-rust/starlark_map",
    "shed/async_std_ext",
    "shed/internment_tweaks",
    "shed/more_futures",
    "superconsole",
    "install_proto",
]

[workspace.dependencies]
anyhow = "1.0.65"
assert_matches = "1.5"
async-compression = { version = "0.3.8", features = ["tokio", "gzip"] }
async-condvar-fair = { version = "0.2.2", features = ["parking_lot_0_11"] }
async-recursion = "1.0"
async-stream = "0.3.2"
async-trait = "0.1.24"
backtrace = "0.3.51"
base64 = "0.13.0"
blake3 = "0.3.7"
bumpalo = "3.8"
byteorder = "1.4.3"
bytes = "1.0"
chrono = "0.4.19"
clap = { version = "3.1.18", features = ["derive", "env"] }
convert_case = "0.4.0"
criterion = { version = "0.3.4", features = ["async", "async_tokio", "html_reports"] }
crossbeam-channel = "0.5"
# crossbeam-epoch=0.9.8 is only compatible with nightly 1.61
crossbeam-epoch = "=0.9.7"
crossterm = "0.23"
daemonize = "0.5"
dashmap = "4.0.2"
derivative = "2.1.1"
derive_more = "0.99.3"
dirs = "3.0.1"
either = "1.5"
enum-iterator = "0.5.0"
enum-map = "0.6.4"
env_logger = "0.7"
faccess = "0.2.3"
fancy-regex = "0.5.0"
flate2 = "1.0.22"
fnv = "1.0.7"
fs2 = "0.4.3"
futures = { version = "0.3.24", features = ["async-await", "compat"] }
futures-intrusive = "0.4"
glob = "0.3.0"
globset = "0.4.7"
hashbrown = { version = "0.12.3", features = ["raw"] }
hex = "0.4.3"
http = "0.2"
httparse = "1.7.1"
humantime = "2.0.1"
indent_write = "2.2.0"
indexmap = { version = "1.9.1", features = ["serde-1"] }
indoc = "1.0.3"
internment = "0.4.0"
inventory = "0.1.10"
itertools = "0.10.3"
jemalloc-ctl = "0.3.3"
jemallocator = { version = "0.3.2", features = ["profiling"] }
libc = "0.2.132"
linked-hash-map = { version = "0.5", features = ["serde_impl"] }
log = "0.4"
lsp-server = "0.5"
lsp-types = "0.93.0"
maplit = "1.0.2"
memchr = "2.4.1"
memmap = "0.7.0"
multimap = "0.8.3"
nix = "0.22"
nom = "6.1.2"
num_cpus = "1.11"
object = "0.25.3"
once_cell = "1.3"
os_str_bytes = "6.0"
owning_ref = "0.4.1"
parking_lot = { version = "0.11.2", features = ["send_guard"] }
pin-project = "0.4.29"
plist = "0.5"
pretty_assertions = "0.6"
proc-macro2 = "1.0"
prost = "0.10"
prost-types = "0.10"
quote = "1.0.3"
rand = { version = "0.8.4", features = ["small_rng"] }
ref-cast = "1.0.0"
regex = "1.3.4"
relative-path = { version = "1.7.0", features = ["serde"] }
reqwest = { version = "0.11.4", features = ["stream"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }
sequence_trie = "0.3.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.48"
sha-1 = "0.10"
sha2 = "0.10"
shlex = "1.1"
siphasher = "0.3.5"
slog = "2.7.0"
smallvec = "1.7"
smartstring = "0.2.9"
static_assertions = "1.1.0"
strsim = "0.10.0"
structopt = "0.3.0"
syn = { version = "1.0.27", features = ["extra-traits", "full"] }
sync_wrapper = "0.1.0"
sys-info = "0.8.0"
take_mut = "0.2.2"
tempfile = "3.1.0"
termimad = "0.20.1"
termios = "0.3"
termwiz = "0.18"
test-case = "1.2.0"
textwrap = "0.15"
thiserror = "1.0.36"
threadpool = "1.8.1"
tokio = { version = "1.5", features = ["full"] }
tokio-rusqlite = "0.3.0"
tokio-stream = { version = "0.1.4", features = ["fs", "io-util", "net", "sync", "time"] }
tokio-util = { version = "0.7.1", features = ["full"] }
toml = "=0.5.8"
tonic = "0.7.2"
tonic-build = { version = "0.7.2", features = ["prost"] }
tower = "0.4"
tower-layer = "0.3.1"
tower-service = "0.3.2"
tracing = "0.1.22"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
trybuild = "1.0.56"
twox-hash = "1.6.1"
uuid = { version = "0.8", features = ["v4"] }
walkdir = "2.3.2"
winapi = { version = "0.3", features = ["everything"] }
xattr = "0.2.2"
zip = "0.5"
zstd = "0.11.1"

fbinit.version = "0.1"
# @oss-disable: fbinit.path = "../common/rust/shed/fbinit"
sorted_vector_map.version = "0.1"
# @oss-disable: sorted_vector_map.path = "../common/rust/shed/sorted_vector_map"

gazebo.version = "0.8.0"
gazebo.features = ["str_pattern_extensions"]
# @oss-disable: gazebo.path = "gazebo/gazebo"
host_sharing = { path = "host_sharing" }
more_futures = { path = "shed/more_futures" }
remote_execution = { path = "remote_execution/stub" }
starlark = { version = "0.9.0-pre", path = "starlark-rust/starlark" }
starlark_map = { version = "0.9.0-pre", path = "starlark-rust/starlark_map" }

[profile.release]
incremental = true
panic = "abort"
# The line below increases build times from 50s to 84s, with no observed impact on runtime speed.
# But maybe for some benchmarks it will show more noticable variation.
# lto = "thin"

# Use with: --profile=release-symbols -Z unstable-options
[profile.release-symbols]
incremental = true
inherits = "release"
debug = true

[profile.dev]
incremental = true
debug = true
panic = "abort"
split-debuginfo = "unpacked"
opt-level = 1

[profile.test]
incremental = true

[profile.bench]
incremental = true

[patch.crates-io]
# Waiting for a release of 0.5.
daemonize = { git = "https://github.com/krallin/daemonize", rev = "f7be28efa1b4a70e43bb37b5f4ff4d664992edca" }
