cargo-features = ["workspace-inheritance"]

[package]
name = "cli_proto"

edition = "2021"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }

buck2_data = { path = "../buck2_data" }

[build-dependencies]
tonic-build = { workspace = true }
