[package]
edition = "2024"
license = { workspace = true }
name = "buck2_build_info"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
buck2_util = { workspace = true }

[lints]
workspace = true
