[package]
name = "starlark_map"
edition = "2021"
version = "0.9.0"
license = "Apache-2.0"
description = "Map implementation with starlark-rust specific optimizations"
documentation = "https://docs.rs/starlark_map"
repository = "https://github.com/facebookexperimental/starlark-rust"
authors = [
    "Facebook"
]

[dependencies]
dupe = { workspace = true }
allocative = { workspace = true, features = ["hashbrown"] }

fnv = "1.0.7"
hashbrown = { version = "0.12.3", features = ["raw"] }
equivalent = { workspace = true }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.48"
