[package]
name = "buck2_forkserver_proto"

edition = "2021"
license = { workspace = true }
repository = { workspace = true }
version = "0.1.0"

[dependencies]
derive_more = { workspace = true }
gazebo = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }

buck2_data = { workspace = true }

[build-dependencies]
buck2_protoc_dev = { workspace = true }
