[package]
authors = ["Meta"]
categories = ["command-line-interface"]
description = "A simple but powerful Text-based User Interface (TUI) framework"
documentation = "https://docs.rs/superconsole"
edition = "2024"
keywords = ["TUI"]
license = "MIT OR Apache-2.0"
name = "superconsole"
repository = "https://github.com/facebookincubator/superconsole"
version = "0.2.0"

[dependencies]
crossbeam-channel = "0.5"
crossterm = "0.28"
itertools = "0.14.0"
termwiz = "0.23"
thiserror = "2.0.18"
unicode-segmentation = "1.12.0"

[dev-dependencies]
anyhow = "1.0.98"
derive_more = { version = "1.0.0", features = ["full"] }
tokio = { version = "1.5", features = ["macros", "rt-multi-thread", "time"] }
