[package]
description = "Query server commands for Buck2"
edition = "2024"
license = { workspace = true }
name = "buck2_cmd_query_server"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
indent_write = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
starlark_map = { workspace = true }

buck2_build_api = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_fs = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_node = { workspace = true }
buck2_profile = { workspace = true }
buck2_query = { workspace = true }
buck2_server_ctx = { workspace = true }
buck2_util = { workspace = true }

[lints]
workspace = true
