[package]
description = "Buck V2 test runner"
edition = "2024"
license = { workspace = true }
name = "buck2_test"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
derive_more = { workspace = true }
display_container = { workspace = true }
futures = { workspace = true }
fxhash = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
host_sharing = { workspace = true }
remote_execution = { workspace = true }
sorted_vector_map = { workspace = true }
starlark = { workspace = true }

buck2_build_api = { workspace = true }
buck2_build_signals = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_downward_api = { workspace = true }
buck2_error = { workspace = true }
buck2_error_derive = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_execute_impl = { workspace = true }
buck2_fs = { workspace = true }
buck2_grpc = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
buck2_node = { workspace = true }
buck2_resource_control = { workspace = true }
buck2_server_ctx = { workspace = true }
buck2_test_api = { workspace = true }
buck2_util = { workspace = true }
dice_futures = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[dev-dependencies]
maplit = { workspace = true }

[lints]
workspace = true
