[package]
name = "fuzzy_dice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
async-trait = "0.1.24"
clap = { version = "3.1.18", features = ["derive"] }
crossbeam = "0.8"
derive_more = "0.99.3"
derivative = "2.1.1"
futures = "0.3"
quickcheck = "1.0"
quickcheck_async = "0.1.1"
ref-cast = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.48"
thiserror = "1.0.9"
tokio = { version = "1.5", features = ["full"]}
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

gazebo.version = "0.8.0"
gazebo.features = ["str_pattern_extensions"]
# @oss-disable: gazebo.path = "../../gazebo/gazebo"
gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"

dice = { path = "../dice" }

[dev-dependencies]
# Newer cast pull in semver 1.0, which fails with
# https://github.com/dtolnay/semver/issues/251
futures = "0.3"
anyhow = "1.0.51"

[features]
# @oss-disable: default = ["gazebo_lint"]
