[package]
name = "buck2_event_observer"
version = "0.1.0"
edition = "2021"
description = "utilities to interpret the buck2 event stream"

[dependencies]
anyhow = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_events = { workspace = true }
buck2_test_api = { workspace = true }
clap = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
dupe = { workspace = true }
itertools = { workspace = true }
linked-hash-map = { workspace = true }
shlex = { workspace = true }
superconsole = { version = "0.1.0", path = "../../superconsole" }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
