[package]
description = "utilities to interpret the buck2 event stream"
edition = "2021"
license = { workspace = true }
name = "buck2_event_observer"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
starlark_map = { workspace = true }

anyhow = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_health_check = { workspace = true }
buck2_test_api = { workspace = true }
buck2_util = { workspace = true }
buck2_wrapper_common = { workspace = true }
clap = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
linked-hash-map = { workspace = true }
regex = { workspace = true }
shlex = { workspace = true }
superconsole = { version = "0.2.0", path = "../../superconsole" }
termwiz = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
