[package]
name = "buck2_analysis"
version = "0.1.0"
edition = "2021"
description = "Execute rule function"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
starlark = { workspace = true }

buck2_build_api = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_node = { workspace = true }
buck2_query = { workspace = true }
