[package]
description = "Interpreter setup to BUCK files"
edition = "2024"
license = { workspace = true }
name = "buck2_interpreter_for_build"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
bumpalo = { workspace = true }
cmp_any = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
fancy-regex = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
hashbrown = { workspace = true }
hex = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
maplit = { workspace = true }
once_cell = { workspace = true }
quick-xml = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
smallvec = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
twox-hash = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
starlark = { workspace = true }
starlark_map = { workspace = true }

buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_event_observer = { workspace = true }
buck2_events = { workspace = true }
buck2_fs = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_node = { workspace = true }
buck2_query = { workspace = true }
buck2_query_parser = { workspace = true }
buck2_util = { workspace = true }
dice_futures = { workspace = true }
