[package]
name = "buck2_interpreter_for_build"
version = "0.1.0"
edition = "2021"
description = "Interpreter setup to BUCK files"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bumpalo = { workspace = true }
ctor = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
hashbrown = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
maplit = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
twox-hash = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
gazebo = { workspace = true }
more_futures = { workspace = true }
dupe = { workspace = true }
starlark = { workspace = true }
starlark_map = { workspace = true }

buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_events = { workspace = true }
buck2_node = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_query = { workspace = true }
buck2_query_parser = { workspace = true }
buck2_util = { workspace = true }
