[package]
description = "`buck2 log` command client implementation"
edition = "2024"
license = { workspace = true }
name = "buck2_cmd_log_client"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
csv = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
linked-hash-map = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

buck2_cli_proto = { workspace = true }
buck2_client_ctx = { workspace = true }
buck2_common = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_event_log = { workspace = true }
buck2_event_observer = { workspace = true }
buck2_events = { workspace = true }
buck2_util = { workspace = true }
buck2_wrapper_common = { workspace = true }
dupe = { workspace = true }

superconsole = { version = "0.2.0", path = "../../superconsole" }

[lints]
workspace = true
