[package]
description = "`buck2 debug` command client implementation"
edition = "2024"
license = { workspace = true }
name = "buck2_cmd_debug_client"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
humantime = { workspace = true }
lsp-types = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }

allocative = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_client_ctx = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_event_log = { workspace = true }
buck2_event_observer = { workspace = true }
buck2_events = { workspace = true }
buck2_fs = { workspace = true }
buck2_offline_archive = { workspace = true }
buck2_wrapper_common = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(buck_build)"] }
