[package]
edition = "2021"
license = { workspace = true }
name = "pagable"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
dupe = { workspace = true }
pagable_derive = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
static_assertions = { workspace = true }
strong_hash = { workspace = true }
triomphe = { workspace = true }
