[package]
edition = "2021"
license = { workspace = true }
name = "pagable"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
bytemuck = { workspace = true }
dashmap = { workspace = true }
dupe = { workspace = true }
either = { workspace = true }
erased-serde = { workspace = true }
gazebo = { workspace = true }
num-bigint = { workspace = true }
pagable_derive = { path = "../pagable_derive" }
parking_lot = { workspace = true }
postcard = { workspace = true }
relative-path = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sequence_trie = { workspace = true }
static_assertions = { workspace = true }
strong_hash = { workspace = true }
take_mut = { workspace = true }
tokio = { workspace = true }
triomphe = { workspace = true }
