[package]
description = ""
edition = "2021"
name = "cli"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
backtrace = { workspace = true }
blake3 = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sync_wrapper = { workspace = true }
termimad = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }

dice = { path = "../dice/dice" }
fbinit = { workspace = true }
gazebo = { workspace = true }
gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../gazebo_lint/gazebo_lint"
host_sharing = { path = "../host_sharing" }
starlark = { workspace = true }
# @oss-disable: user = { path = "../../common/rust/user", optional = true }

buck2_audit = { path = "../buck2_audit" }
buck2_build_api = { path = "../buck2_build_api" }
buck2_bxl = { path = "../buck2_bxl" }
buck2_core = { path = "../buck2_core" }
buck2_query = { path = "../buck2_query" }
buck2_client = { path = "../buck2_client" }
buck2_common = { path = "../buck2_common" }
buck2_data = { path = "../buck2_data" }
buck2_events = { path = "../buck2_events" }
buck2_forkserver = { path = "../buck2_forkserver" }
buck2_server = { path = "../buck2_server" }
buck2_server_commands = { path = "../buck2_server_commands" }
buck2_server_ctx = { path = "../buck2_server_ctx" }
buck2_test = { path = "../buck2_test" }
cli_proto = { path = "../cli_proto" }

[target.'cfg(target_os = "linux")'.dependencies]
daemonize = { workspace = true }

[target.'cfg(unix)'.dependencies]
daemonize = { workspace = true }
jemallocator = { workspace = true }

[target.'cfg(windows)'.dependencies]
libc = { workspace = true }
winapi = { workspace = true }

[dev-dependencies]
maplit = { workspace = true }
tempfile = { workspace = true }

[[bin]]
name = "buck2"
path = "bin/buck2.rs"

[features]
# @oss-disable: default = ["gazebo_lint", "eden_materializer"]
eden_materializer = ["buck2_build_api/eden_materializer", "buck2_server/eden_materializer", "buck2_server_commands/eden_materializer"]
