[package]
name = "dupe"
version = "0.8.1"
license = "MIT OR Apache-2.0"
authors = ["Facebook"]
edition = "2021"
description = "Marker for types which are cheap to clone"
repository = "https://github.com/facebookincubator/gazebo"
documentation = "https://docs.rs/dupe"
categories = ["rust-patterns"]

[features]
str_pattern_extensions = []

[dependencies]
dupe_derive = { version = "0.8.0", path = "../dupe_derive" }
