[package]
name = "buck2_interpreter"
version = "0.1.0"
edition = "2021"
description = "Interprets build files and handles loading and interpreting extension files, and communicating this information to DICE"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
hex = { workspace = true }
hashbrown = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
glob = { workspace = true }
plist = { workspace = true }
tokio = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
gazebo = { workspace = true }
dupe = { workspace = true }
gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
more_futures = { path = "../../shed/more_futures" }
starlark = { workspace = true }

buck2_common = { workspace = true }
buck2_core = { workspace = true }

[features]
# @oss-disable: default = ["gazebo_lint"]

[dev-dependencies]
tempfile = { workspace = true }
