[package]
name = "buck2_server_ctx"
version = "0.1.0"
edition = "2021"
description = "Common parts of Buck commands"

[dependencies]
anyhow = { workspace = true }
async-condvar-fair = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
more_futures = { workspace = true }
tokio = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
gazebo = { workspace = true }
dupe = { workspace = true }

# Please do not add dependency on `buck2_build_api`.
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_cli_proto = { workspace = true }
starlark_map = { workspace = true }

[dev-dependencies]
derivative = { workspace = true }
tokio = { workspace = true }
