omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = 'Unresolved build script at vendor/core-foundation-sys-0.8.3/build.rs. Dependencies:'

[extra_mapped_srcs]

[platform_fixup]
