[package]
description = "Target graph node"
edition = "2024"
license = { workspace = true }
name = "buck2_node"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
memchr = { workspace = true }
once_cell = { workspace = true }
ref-cast = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smallvec = { workspace = true }
static_assertions = { workspace = true }
static_interner = { workspace = true }
strsim = { workspace = true }
triomphe = { workspace = true }

allocative = { workspace = true }
cmp_any = { workspace = true }
dice = { workspace = true }
display_container = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
pagable = { workspace = true }
starlark_map = { workspace = true }
strong_hash = { workspace = true }

buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_fs = { workspace = true }
buck2_query = { workspace = true }
buck2_query_parser = { workspace = true }
buck2_util = { workspace = true }
dice_futures = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
