[package]
description = "Target graph node"
edition = "2021"
name = "buck2_node"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
fnv = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
ref-cast = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
static_assertions = { workspace = true }
strsim = { workspace = true }

allocative = { workspace = true }
cmp_any = { workspace = true }
dice = { workspace = true }
display_container = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
gazebo_lint.version = "0.1"
starlark_map = { workspace = true }

buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_query = { workspace = true }
buck2_query_parser = { workspace = true }
buck2_util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[features]
# @oss-disable: default = ["gazebo_lint"]
