[package]
edition = "2024"
license = { workspace = true }
name = "buck2_execute_local"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
libc = { workspace = true }
pin-project = { workspace = true }
take_mut = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

buck2_common = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_fs = { workspace = true }
buck2_miniperf_proto = { workspace = true }
buck2_resource_control = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
buck2_wrapper_common = { workspace = true }
dupe = { workspace = true }
winapi = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
dupe = { workspace = true }
sysinfo = { workspace = true }
tempfile = { workspace = true }
tokio-stream = { workspace = true }

buck2_util = { workspace = true }

[lints]
workspace = true
