[package]
description = "Implementation of several Buck commands"
edition = "2024"
license = { workspace = true }
name = "buck2_server_commands"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
fxhash = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

dice = { workspace = true }
dupe = { workspace = true }
starlark_map = { workspace = true }

buck2_artifact = { workspace = true }
buck2_build_api = { workspace = true }
buck2_certs = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_directory = { workspace = true }
buck2_error = { workspace = true }
buck2_event_log = { workspace = true }
buck2_event_observer = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_fs = { workspace = true }
buck2_install_proto = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_node = { workspace = true }
buck2_query = { workspace = true }
buck2_server_ctx = { workspace = true }
buck2_util = { workspace = true }

[lints]
workspace = true
