[package]
description = "Anonymous targets"
edition = "2021"
license = { workspace = true }
name = "buck2_anon_target"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

allocative = { workspace = true }
cmp_any = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
starlark = { workspace = true }
starlark_map = { workspace = true }

buck2_analysis = { workspace = true }
buck2_artifact = { workspace = true }
buck2_build_api = { workspace = true }
buck2_configured = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_futures = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
buck2_node = { workspace = true }
buck2_util = { workspace = true }
