[package]
name = "buck2_common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
chrono = { workspace = true }
compact_str = { workspace = true }
dashmap = { workspace = true }
derive_more = { workspace = true }
digest = { workspace = true }
dirs = { workspace = true }
faccess = { workspace = true }
futures = { workspace = true }
globset = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
hyper-proxy = { workspace = true }
hyper-rustls = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
once_cell = { workspace = true }
prost-types = { workspace = true }
rand = { workspace = true }
ref-cast = { workspace = true }
regex = { workspace = true }
rusqlite = { workspace = true }
rustls = { workspace = true }
rustls-native-certs = { workspace = true }
rustls-pemfile = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
num_enum = { workspace = true }
derivative = { workspace = true }
parking_lot = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }


allocative = { workspace = true }
dice = { workspace = true }
# @oss-disable: edenfs = { package = "thrift", path = "../../../eden/fs/service" }
fbinit = { workspace = true }
# @oss-disable: fb303_core = { package = "fb303_core", path = "../../../fb303/thrift" }
gazebo = { workspace = true }
dupe = { workspace = true }
gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
internment_tweaks = { path = "../../shed/internment_tweaks" }
more_futures = { workspace = true }
sorted_vector_map = { workspace = true }

buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_events = { workspace = true }
buck2_util = { workspace = true }

[target.'cfg(unix)'.dependencies]
hyper-unix-connector = { workspace = true }
nix = { workspace = true }
tower = { workspace = true }
xattr = { workspace = true }

[features]
# @oss-disable: default = ["gazebo_lint"]

[dev-dependencies]
indoc = { workspace = true }
maplit = { workspace = true }
assert_matches = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
httptest = { workspace = true }
