[package]
edition = "2024"
license = { workspace = true }
name = "buck2_common"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-scoped = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
compact_str = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
digest = { workspace = true }
dirs = { workspace = true }
fbinit = { workspace = true }
fs4 = { workspace = true }
futures = { workspace = true }
globset = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
num_enum = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
prost-types = { workspace = true }
rand = { workspace = true }
ref-cast = { workspace = true }
regex = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
smallvec = { workspace = true }
strsim = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
triomphe = { workspace = true }

allocative = { workspace = true }
cmp_any = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
pagable = { workspace = true }
starlark_map = { workspace = true }

buck2_cli_proto = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_fs = { workspace = true }
buck2_http = { workspace = true }
buck2_util = { workspace = true }
buck2_wrapper_common = { workspace = true }
dice_futures = { workspace = true }

[target.'cfg(unix)'.dependencies]
hyper-util = { workspace = true }
nix = { workspace = true }
tower = { workspace = true }
xattr = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
indoc = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fbcode_build)"] }
