[package]
description = "Artifact types"
edition = "2021"
license = { workspace = true }
name = "buck2_artifact"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
derivative = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
serde = { workspace = true }
static_assertions = { workspace = true }
take_mut = { workspace = true }

allocative = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
starlark_map = { workspace = true }

buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_execute = { workspace = true }
buck2_util = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
serde_json = { workspace = true }
