[package]
description = "Supporting code and utilities for manipulating offline build archives"
edition = "2021"
name = "buck2_offline_archive"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }

buck2_core = { workspace = true }
