[package]
description = "Build related interpreter defs, coercion logic, some build rule impelementations, and handing actions off to DICE for caching and execution. A large chunk of the 'build' part of BuckV2"
edition = "2024"
license = { workspace = true }
name = "buck2_build_api"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-recursion = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
blake3 = { workspace = true }
console = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
fxhash = { workspace = true }
indexmap = { workspace = true }
internment = { workspace = true }
inventory = { workspace = true }
itertools = { workspace = true }
linkme = { workspace = true }
multimap = { workspace = true }
once_cell = { workspace = true }
probminhash = { workspace = true }
ref-cast = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smallvec = { workspace = true }
static_assertions = { workspace = true }
strong_hash = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
display_container = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
pagable = { workspace = true }
remote_execution = { workspace = true }
rustls = { workspace = true }
setsketch = { workspace = true }
sorted_vector_map = { workspace = true }
starlark = { workspace = true }
starlark_map = { workspace = true }

buck2_artifact = { workspace = true }
buck2_build_api_derive = { workspace = true }
buck2_build_info = { workspace = true }
buck2_build_signals = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_directory = { workspace = true }
buck2_error = { workspace = true }
buck2_errorformat = { workspace = true }
buck2_event_observer = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_file_watcher = { workspace = true }
buck2_fs = { workspace = true }
buck2_http = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_node = { workspace = true }
buck2_query = { workspace = true }
buck2_test_api = { workspace = true }
buck2_util = { workspace = true }
buck2_wrapper_common = { workspace = true }
dice_futures = { workspace = true }

[dev-dependencies]
buck2_certs = { workspace = true }
buck2_wrapper_common = { workspace = true }
