[package]
description = """
Unsorted utilities used by buck2. Not specific to buck2, generic enough to be used by other projects.
but not generic or stable enough to be published on crates.io as standalone crates.
"""
edition = "2024"
license = { workspace = true }
name = "buck2_util"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
blake3 = { workspace = true }
dupe = { workspace = true }
futures = { workspace = true }
pagable = { workspace = true }
starlark_map = { workspace = true }
strong_hash = { workspace = true }
sysinfo = { workspace = true }
tracing = { workspace = true }
triomphe = { workspace = true }

buck2_env = { workspace = true }
buck2_error = { workspace = true }
buck2_wrapper_common = { workspace = true }
serde = { workspace = true }
static_assertions = { workspace = true }
tokio = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
perf-event = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

three_billion_instructions = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(debug)", "cfg(buck2_asan)"] }
