[package]
name = "host_sharing"
version = "0.1.0"
authors = ["Logan Wendholt <lwendholt@fb.com>"]
edition = "2021"

[dependencies]
dashmap = { workspace = true }
futures-intrusive = { workspace = true }
