[package]
edition = "2021"
license = { workspace = true }
name = "buck2_core"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
blake3 = { workspace = true }
compact_str = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
dunce = { workspace = true }
either = { workspace = true }
equivalent = { workspace = true }
futures = { workspace = true }
hostname = { workspace = true }
indent_write = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
linkme = { workspace = true }
memchr = { workspace = true }
once_cell = { workspace = true }
os_str_bytes = { workspace = true }
pin-project = { workspace = true }
rand = { workspace = true }
ref-cast = { workspace = true }
regex = { workspace = true }
relative-path = { workspace = true }
sequence_trie = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
starlark_map = { workspace = true }
static_assertions = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
triomphe = { workspace = true }

allocative = { workspace = true }
cmp_any = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
lock_free_hashtable = { workspace = true }
sorted_vector_map = { workspace = true }
static_interner = { path = "../../shed/static_interner" }

buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_util = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
common-path = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
maplit = { workspace = true }
serde_json = { workspace = true }
test-case = { workspace = true }
