[package]
edition = "2024"
license = { workspace = true }
name = "buck2_core"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
blake3 = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
equivalent = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hostname = { workspace = true }
indent_write = { workspace = true }
itertools = { workspace = true }
memchr = { workspace = true }
once_cell = { workspace = true }
os_str_bytes = { workspace = true }
pagable = { workspace = true }
pin-project = { workspace = true }
rand = { workspace = true }
ref-cast = { workspace = true }
regex = { workspace = true }
relative-path = { workspace = true }
sequence_trie = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
starlark_map = { workspace = true, features = ["pagable_dep"] }
static_assertions = { workspace = true }
strong_hash = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
triomphe = { workspace = true }

allocative = { workspace = true }
cmp_any = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
lock_free_hashtable = { workspace = true }
static_interner = { workspace = true }

buck2_data = { workspace = true }
buck2_env = { workspace = true }
buck2_error = { workspace = true }
buck2_fs = { workspace = true }
buck2_util = { workspace = true }

[target.'cfg(windows)'.dependencies]
common-path = { workspace = true }
winapi = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
serde_json = { workspace = true }
test-case = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fbcode_build)"] }
