[package]
name = "internment_tweaks"
version = "0.1.0"
edition = "2021"
description = "Similar to `internment` crate, but with interface and performance tweaks"

[dependencies]
gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
gazebo = { workspace = true }
dupe = { workspace = true }
allocative = { workspace = true }
lock_free_hashtable = { workspace = true }

[features]
# @oss-disable: default = ["gazebo_lint"]
