[package]
description = ""
edition = "2021"
name = "buck2_daemon"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
clap = { workspace = true }
futures = { workspace = true }
libc = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }

buck2_cli_proto = { workspace = true }
buck2_client_ctx = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_server = { workspace = true }
buck2_util = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }

[dev-dependencies]
fbinit = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(buck_build)", "cfg(client_only)", "cfg(fbcode_build)"] }
