[package]
description = """
Library providing an `anyhow` inspired error type for buck2
"""
edition = "2024"
license = { workspace = true }
name = "buck2_error"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
fancy-regex = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
libc = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
ref-cast = { workspace = true }
regex = { workspace = true }
relative-path = { workspace = true }
rusqlite = { workspace = true }
rustls-native-certs = { workspace = true }
rustls-pki-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tonic = { workspace = true }
uuid = { workspace = true }

allocative = { workspace = true }
dice_error = { workspace = true }
dupe = { workspace = true }
superconsole = { version = "0.2.0", path = "../../superconsole" }
# @oss-disable: watchman_client.path = "../../../watchman/rust/watchman_client"
watchman_client.version = "0.9.0"

buck2_data = { workspace = true }
buck2_error_derive = { workspace = true }

starlark_syntax = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fbcode_build)"] }
