omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = '''
Unresolved build script at vendor/proc-macro-error-attr-1.0.4/build.rs. Dependencies:
    version_check-0.9.4'''

[extra_mapped_srcs]

[platform_fixup]
