[package]
name = "starlark_derive"
version = "0.9.0-pre"
edition = "2021"
license = "Apache-2.0"
description = "Derive helpers for the starlark package."
documentation = "https://docs.rs/starlark_derive"
repository = "https://github.com/facebookexperimental/starlark-rust"
authors = ["Facebook"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0.96", features = ["full", "extra-traits", "visit"] }
dupe = { workspace = true }
quote = "1.0"
