[package]
edition = "2024"
license = { workspace = true }
name = "buck2_grpc"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
buck2_error = { workspace = true }
futures = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
pin-project = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
