[package]
edition = "2024"
license = { workspace = true }
name = "buck2_env"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
arc-swap = { workspace = true }
linkme = { workspace = true }
once_cell = { workspace = true }
starlark_map = { workspace = true }
tracing = { workspace = true }

dupe = { workspace = true }

buck2_error = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }

[lints]
workspace = true
