[package]
description = "Client side of `buck2 audit`"
edition = "2021"
license = { workspace = true }
name = "buck2_audit"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

dupe = { workspace = true }

buck2_cli_proto = { workspace = true }
buck2_client_ctx = { workspace = true }
