[package]
description = "Code supporting buck2 client commands"
edition = "2021"
name = "buck2_client_ctx"
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
anyhow = { workspace = true }
async-compression = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
crossterm = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
fs2 = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
httparse = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
linked-hash-map = { workspace = true }
memmap2 = { workspace = true }
object = { workspace = true }
once_cell = { workspace = true }
pin-project = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shlex = { workspace = true }
sysinfo = { workspace = true }
termwiz = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
gazebo = { workspace = true }
dupe = { workspace = true }
fbinit = { workspace = true }
which = "4.2.4"

# @oss-disable: hostcaps = { path = "../../../common/rust/shed/hostcaps" }
superconsole = { version = "0.1.0", path = "../../superconsole" }

# Please do not add dependency on `buck2_build_api`.
buck2_build_info = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_events = { workspace = true }
buck2_test_api = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_util = { workspace = true }
buck2_event_observer = { workspace = true }
buck2_wrapper_common = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }
termios = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }

[dev-dependencies]
assert_matches= { workspace = true }
lsp-server = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
