[package]
description = "Code supporting buck2 client commands"
edition = "2024"
license = { workspace = true }
name = "buck2_client_ctx"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
async-compression = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
console = { workspace = true }
crossterm = { workspace = true }
csv = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
dupe = { workspace = true }
fbinit = { workspace = true }
fs4 = { workspace = true }
futures = { workspace = true }
gazebo = { workspace = true }
hex = { workspace = true }
httparse = { workspace = true }
humantime = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
memmap2 = { workspace = true }
object = { workspace = true }
once_cell = { workspace = true }
pin-project = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shlex = { workspace = true }
strum = { workspace = true }
sysinfo = { workspace = true }
take_mut = { workspace = true }
termwiz = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

superconsole = { version = "0.2.0", path = "../../superconsole" }

# Please do not add dependency on `buck2_build_api`.
buck2_build_info = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_event_log = { workspace = true }
buck2_event_observer = { workspace = true }
buck2_events = { workspace = true }
buck2_fs = { workspace = true }
buck2_health_check = { workspace = true }
buck2_resource_control = { workspace = true }
buck2_util = { workspace = true }
buck2_wrapper_common = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }
termios = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
indoc = { workspace = true }
lsp-server = { workspace = true }
maplit = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
