# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under both the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree and the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree.

['cfg(all(version = ">=0.48.0", any(target_os = "windows", target_os = "linux")))']
cfgs = ["windows_raw_dylib"]
