[package]
authors = ["Meta"]
description = "Implementation of derive(Pagable) for pagable crate"
edition = "2021"
license = { workspace = true }
name = "pagable_derive"
version = "0.3.3"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
