[package]
description = "Implementation of Buck2 targets command"
edition = "2024"
license = { workspace = true }
name = "buck2_cmd_targets_server"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-recursion = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
derive_more = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
os_str_bytes = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
siphasher = { workspace = true }
tokio = { workspace = true }
zstd = { workspace = true }

dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
starlark_map = { workspace = true }

buck2_artifact = { workspace = true }
buck2_build_api = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_execute = { workspace = true }
buck2_fs = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_node = { workspace = true }
buck2_query = { workspace = true }
buck2_server_ctx = { workspace = true }
buck2_util = { workspace = true }
dice_futures = { workspace = true }

[lints]
workspace = true
