[package]
description = "Remote-execution support for Buck"
edition = "2024"
license = { workspace = true }
name = "buck2_execute"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
crossbeam-channel = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
digest = { workspace = true }
either = { workspace = true }
faccess = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
pathdiff = { workspace = true }
prost = { workspace = true }
ref-cast = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
smallvec = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
fbinit = { workspace = true }
gazebo = { workspace = true }
host_sharing = { workspace = true }
remote_execution = { workspace = true }
sorted_vector_map = { workspace = true }
starlark_map = { workspace = true }
strong_hash = { workspace = true }

buck2_action_metadata_proto = { workspace = true }
buck2_build_info = { workspace = true }
buck2_build_signals = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_directory = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_fs = { workspace = true }
buck2_http = { workspace = true }
buck2_miniperf_proto = { workspace = true }
buck2_re_configuration = { workspace = true }
buck2_util = { workspace = true }
buck2_wrapper_common = { workspace = true }
dice_futures = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
prost-types = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fbcode_build)"] }
