[package]
description = "Remote-execution support for Buck"
edition = "2021"
name = "buck2_execute"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
crossbeam-channel = { workspace = true }
chrono = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
digest = { workspace = true }
either = { workspace = true }
faccess = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
prost = { workspace = true }
reqwest = { workspace = true }
ref-cast = { workspace = true }
serde = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
slog = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }

dice = { workspace = true }
# @oss-disable: edenfs = { package = "thrift", path = "../../../eden/fs/service" }
fbinit = { workspace = true }
gazebo = { workspace = true }
dupe = { workspace = true }
host_sharing = { workspace = true }
more_futures = { workspace = true }
remote_execution = { workspace = true }
sorted_vector_map = { workspace = true }
allocative = { workspace = true }
starlark_map = { workspace = true }

buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_events = { workspace = true }
buck2_util = { workspace = true }
buck2_re_configuration = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
