[package]
authors = ["Meta"]
description = "Interface for build signals"
edition = "2024"
license = { workspace = true }
name = "buck2_build_signals"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
async-trait = { workspace = true }
buck2_core = { workspace = true }
buck2_critical_path = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_fs = { workspace = true }
buck2_util = { workspace = true }
cmp_any = { workspace = true }
derive_more = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
