[package]
edition = "2024"
license = { workspace = true }
name = "buck2_fs"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
compact_str = { workspace = true }
derive_more = { workspace = true }
dunce = { workspace = true }
memchr = { workspace = true }
ref-cast = { workspace = true }
relative-path = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
tokio = { workspace = true }

allocative = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
pagable = { workspace = true }
strong_hash = { workspace = true }

buck2_env = { workspace = true }
buck2_error = { workspace = true }
buck2_util = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
common-path = { workspace = true }
winapi = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
