[package]
description = "Implementations of executors and materializers"
edition = "2021"
name = "buck2_execute_impl"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-condvar-fair = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
dupe = { workspace = true }
faccess = { workspace = true }
futures = { workspace = true }
gazebo = { workspace = true }
host_sharing = { workspace = true }
hostname = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
more_futures = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
pin-project = { workspace = true }
prost = { workspace = true }
remote_execution = { workspace = true }
rusqlite = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
zstd = { workspace = true }

allocative = { workspace = true }

buck2_action_metadata_proto = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_forkserver = { workspace = true }
buck2_forkserver_proto = { workspace = true }
buck2_http = { workspace = true }
buck2_util = { workspace = true }
buck2_worker_proto = { workspace = true }
buck2_wrapper_common = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
