[package]
description = "Implementations of executors and materializers"
edition = "2024"
license = { workspace = true }
name = "buck2_execute_impl"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-condvar-fair = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
dupe = { workspace = true }
futures = { workspace = true }
gazebo = { workspace = true }
host_sharing = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
pin-project = { workspace = true }
prost = { workspace = true }
regex = { workspace = true }
remote_execution = { workspace = true }
rusqlite = { workspace = true }
starlark_map = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
zstd = { workspace = true }

allocative = { workspace = true }

buck2_action_metadata_proto = { workspace = true }
buck2_build_signals = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_directory = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_execute_local = { workspace = true }
buck2_fs = { workspace = true }
buck2_http = { workspace = true }
buck2_resource_control = { workspace = true }
buck2_util = { workspace = true }
buck2_worker_proto = { workspace = true }
buck2_wrapper_common = { workspace = true }
dice_futures = { workspace = true }

[target.'cfg(unix)'.dependencies]
buck2_forkserver = { workspace = true }
buck2_forkserver_proto = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fbcode_build)"] }
