[package]
name = "buck2_forkserver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }
pin-project = { workspace = true }
rand = { workspace = true }
take_mut = { workspace = true }
tokio-util = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

allocative = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
gazebo_lint.version = "0.1"

buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_forkserver_proto = { workspace = true }
buck2_grpc = { workspace = true }
buck2_util = { workspace = true }
buck2_miniperf_proto = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bytes = { workspace = true }
tempfile = { workspace = true }
tokio-stream = { workspace = true }

[features]
# @oss-disable: default = ["gazebo_lint"]
