[package]
edition = "2024"
license = { workspace = true }
name = "buck2_forkserver"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
arc-swap = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }

allocative = { workspace = true }
dupe = { workspace = true }

buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_error = { workspace = true }
buck2_execute_local = { workspace = true }
buck2_forkserver_proto = { workspace = true }
buck2_fs = { workspace = true }
buck2_grpc = { workspace = true }
buck2_resource_control = { workspace = true }
buck2_util = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }

[lints]
workspace = true
