[package]
description = "Some parts of Buck2 server"
edition = "2024"
license = { workspace = true }
name = "buck2_server"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-recursion = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
buck2_re_configuration = { workspace = true }
chrono = { workspace = true }
constant_time_eq = { workspace = true }
crossbeam-channel = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
host_sharing = { workspace = true }
inferno = { workspace = true }
itertools = { workspace = true }
lsp-server = { workspace = true }
lsp-types = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
pin-project = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
shlex = { workspace = true }
sync_wrapper = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
fbinit = { workspace = true }
gazebo = { workspace = true }
starlark = { workspace = true }
starlark_lsp = { workspace = true }

buck2_analysis = { workspace = true }
buck2_build_api = { workspace = true }
buck2_build_signals = { workspace = true }
buck2_certs = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_common = { workspace = true }
buck2_configured = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_directory = { workspace = true }
buck2_error = { workspace = true }
buck2_event_observer = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_execute_impl = { workspace = true }
buck2_file_watcher = { workspace = true }
buck2_fs = { workspace = true }
buck2_http = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
buck2_node = { workspace = true }
buck2_profile = { workspace = true }
buck2_resource_control = { workspace = true }
buck2_server_ctx = { workspace = true }
buck2_server_starlark_debug = { workspace = true }
buck2_subscription_proto = { workspace = true }
buck2_test = { workspace = true }
buck2_util = { workspace = true }
buck2_validation = { workspace = true }
buck2_wrapper_common = { workspace = true }
dice_futures = { workspace = true }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
buck2_forkserver = { workspace = true }
psutil = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
buck2_util = { workspace = true }
indoc = { workspace = true }

[lints]
workspace = true
