[package]
description = ""
edition = "2021"
name = "buck2"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
backtrace = { workspace = true }
blake3 = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
# @oss-disable: hostcaps = { path = "../../../common/rust/shed/hostcaps" }
itertools = { workspace = true }
libc = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sync_wrapper = { workspace = true }
termimad = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
which = "4.2.4"

dice = { workspace = true }
fbinit = { workspace = true }
gazebo = { workspace = true }
dupe = { workspace = true }
gazebo_lint.version = "0.1"
gazebo_lint.optional = true
# @oss-disable: gazebo_lint.path = "../../gazebo_lint/gazebo_lint"
host_sharing = { workspace = true }
starlark = { workspace = true }
# @oss-disable: user = { path = "../../../common/rust/user", optional = true }
allocative = { workspace = true }

buck2_audit = { workspace = true }
buck2_build_api = { workspace = true }
buck2_bxl = { workspace = true }
buck2_core = { workspace = true }
buck2_query = { workspace = true }
buck2_client = { workspace = true }
buck2_client_ctx = { workspace = true }
buck2_common = { workspace = true }
buck2_data = { workspace = true }
buck2_event_observer = { workspace = true }
buck2_events = { workspace = true }
buck2_forkserver = { workspace = true }
buck2_server = { workspace = true }
buck2_server_commands = { workspace = true }
buck2_server_ctx = { workspace = true }
buck2_starlark = { workspace = true }
buck2_test = { workspace = true }
buck2_test_runner = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_util = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { workspace = true }
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
libc = { workspace = true }
winapi = { workspace = true }

[dev-dependencies]
maplit = { workspace = true }
tempfile = { workspace = true }

[[bin]]
name = "buck2"
path = "bin/buck2.rs"

[features]
# @oss-disable: default = ["gazebo_lint"]
