[package]
authors = ["Facebook"]
categories = ["rust-patterns"]
description = "Utilities to implement Display"
documentation = "https://docs.rs/display_container"
edition = "2021"
license = { workspace = true }
name = "display_container"
repository = "https://github.com/facebookincubator/gazebo"
version = "0.9.0"

[dependencies]
either = { workspace = true }
indenter = { workspace = true }
