[package]
description = "`buck2 rage` command client implementation"
edition = "2024"
license = { workspace = true }
name = "buck2_cmd_rage_client"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
dupe = { workspace = true }
futures = { workspace = true }
humantime = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

# Buck2 dependencies
buck2_cli_proto = { workspace = true }
buck2_client_ctx = { workspace = true }
buck2_cmd_audit_client = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_event_log = { workspace = true }
buck2_events = { workspace = true }
buck2_fs = { workspace = true }
buck2_util = { workspace = true }
buck2_wrapper_common = { workspace = true }

[lints]
workspace = true
