[package]
description = "Some parts of Buck client"
edition = "2021"
name = "buck2_client"
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
anyhow = { workspace = true }
async-compression = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
bytesize = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
crossterm = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
humantime = { workspace = true }
indexmap = { workspace = true }
libc = { workspace = true }
lsp-server = { workspace = true }
maplit = { workspace = true }
multimap = { workspace = true }
once_cell = { workspace = true }
prost-types = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shlex = { workspace = true }
termwiz = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }
num_cpus = { workspace = true }
threadpool = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
superconsole = { version = "0.1.0", path = "../../superconsole" }

# Please do not add dependency on `buck2_build_api`.
buck2_audit = { workspace = true }
buck2_client_ctx = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_execute = { workspace = true }
buck2_event_observer = { workspace = true }
buck2_events = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_query_common = { workspace = true }
buck2_util = { workspace = true }
buck2_subscription_proto = { workspace = true }
buck2_offline_archive = { workspace = true }
buck2_wrapper_common = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
tempfile = { workspace = true }
