[package]
description = "Some parts of Buck client"
edition = "2024"
license = { workspace = true }
name = "buck2_client"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-recursion = { workspace = true }
async-trait = { workspace = true }
bytesize = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
dupe = { workspace = true }
futures = { workspace = true }
gazebo = { workspace = true }
humantime = { workspace = true }
libc = { workspace = true }
lsp-server = { workspace = true }
maplit = { workspace = true }
multimap = { workspace = true }
once_cell = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shlex = { workspace = true }
superconsole = { version = "0.2.0", path = "../../superconsole" }
threadpool = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
walkdir = { workspace = true }

# Please do not add dependency on `buck2_build_api`.
buck2_cli_proto = { workspace = true }
buck2_client_ctx = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_event_log = { workspace = true }
buck2_fs = { workspace = true }
buck2_query_parser = { workspace = true }
buck2_subscription_proto = { workspace = true }
buck2_util = { workspace = true }
buck2_wrapper_common = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
tempfile = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fbcode_build)"] }
