[package]
name = "buck2_action_impl"
version = "0.1.0"
edition = "2021"
description = "Action implementations and context functions"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
ctor = { workspace = true }
dashmap = { workspace = true }
derive_more = { workspace = true }
dupe = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
relative-path = { workspace = true }
sha1 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

allocative = { workspace = true }
gazebo = { workspace = true }
sorted_vector_map = { workspace = true }
starlark = { workspace = true }
starlark_map = { workspace = true }

buck2_build_api = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_execute = { workspace = true }
buck2_events = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
host_sharing = { workspace = true }
remote_execution = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }
maplit = { workspace = true }

buck2_node = { workspace = true }
