[package]
description = "Action implementations and context functions"
edition = "2024"
license = { workspace = true }
name = "buck2_action_impl"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
derive_more = { workspace = true }
dupe = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
fxhash = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
relative-path = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
smallvec = { workspace = true }
static_assertions = { workspace = true }
tracing = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
gazebo = { workspace = true }
sorted_vector_map = { workspace = true }
starlark = { workspace = true }
starlark_map = { workspace = true }

buck2_action_metadata_proto = { workspace = true }
buck2_analysis = { workspace = true }
buck2_artifact = { workspace = true }
buck2_build_api = { workspace = true }
buck2_build_signals = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_directory = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_execute = { workspace = true }
buck2_file_watcher = { workspace = true }
buck2_fs = { workspace = true }
buck2_http = { workspace = true }
buck2_interpreter = { workspace = true }
buck2_node = { workspace = true }
buck2_util = { workspace = true }
dice_futures = { workspace = true }
host_sharing = { workspace = true }
remote_execution = { workspace = true }
