[package]
name = "gazebo_derive"
version = "0.8.0"
license = "MIT OR Apache-2.0"
authors = ["Facebook"]
edition = "2021"
description = "Derive macros for the Gazebo library"
repository = "https://github.com/facebookincubator/gazebo"
documentation = "https://docs.rs/gazebo_derive"
categories = ["rust-patterns"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2", features = ["extra-traits"] }
quote = "1.0.3"
