[package]
authors = ["Facebook"]
categories = ["rust-patterns"]
description = "Derive macros for the Gazebo library"
documentation = "https://docs.rs/gazebo_derive"
edition = "2021"
license = { workspace = true }
name = "gazebo_derive"
repository = "https://github.com/facebookincubator/gazebo"
version = "0.8.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0.3"
syn = { version = "2", features = ["extra-traits"] }
