[package]
name = "buck2_build_signals_impl"
version = "0.1.0"
edition = "2021"
description = "Capture build signals during a build to produce a critical path"
license = "MIT OR Apache-2.0"
authors = ["Meta"]

[dependencies]
anyhow = { workspace = true }
derive_more = { workspace = true }
itertools = { workspace = true }
smallvec = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
allocative = { workspace = true }
buck2_artifact = { workspace = true }
buck2_build_api = { workspace = true }
buck2_core = { workspace = true }
buck2_critical_path = { workspace = true }
buck2_data = { workspace = true }
buck2_events = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
buck2_node = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
gazebo = { workspace = true }
static_assertions = { workspace = true }
