[package]
description = "Buck2 file watcher"
edition = "2024"
license = { workspace = true }
name = "buck2_file_watcher"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
notify = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

allocative = { workspace = true }
blake3 = { workspace = true }
compact_str = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
fbinit = { workspace = true }
hex = { workspace = true }
starlark_map = { workspace = true }
# @oss-disable: watchman_client.path = "../../../watchman/rust/watchman_client"
watchman_client.version = "0.9.0"

buck2_certs = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_fs = { workspace = true }
buck2_util = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
assert_matches = { workspace = true }
buck2_util = { workspace = true }
gazebo = { workspace = true }

[lints]
workspace = true
