[package]
description = "Buck2 file watcher"
edition = "2021"
name = "buck2_file_watcher"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
notify = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

allocative = { workspace = true }
dupe = { workspace = true }
dice = { workspace = true }
starlark_map = { workspace = true }
watchman_client.version = "0.8.0"
# @oss-disable: watchman_client.path = "../../../watchman/rust/watchman_client"

buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_events = { workspace = true }
buck2_util = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
tempfile = { workspace = true }
buck2_util = { workspace = true }
gazebo = { workspace = true }
